sample_ids: ["SRR935090","SRR935091","SRR935092"]
sample_ids_geo: ["GSM1186459", "GSM1186460", "GSM1186461"]

# Maximal number of reads to retrieve for each run. This is to reduce the time
# and space needed for this tutorial. Use a very large number, such as 100000000,
# if you want to use the full files.
max_reads: 25000
